args <- commandArgs(trailingOnly = FALSE)
script_path <- normalizePath(sub("^--file=", "", args[grepl("^--file=", args)][1]), winslash = "/", mustWork = TRUE)
project <- normalizePath(file.path(dirname(script_path), ".."), winslash = "/", mustWork = TRUE)
setwd(project)
Sys.setenv(USS_TERROR_PROJECT = project)
source("R/helpers.R")
source("R/mine_sources.R")
source("R/minefield_models.R")
source("R/minefield_validation.R")
settings <- load_settings()
tables <- write_empty_mine_database(crs = settings$crs)
issues <- write_mine_validation_report(tables, settings)
if (any(issues$severity == "error")) stop("Mine schema validation failed.", call. = FALSE)
message("Empty canonical mine-warfare schema built successfully; no historical records were added.")
